### index handler
# http://localhost:8080/ 有冲突，用 http://127.0.0.1:8080/ 又没反应
# 可以用浏览器打开，或者在命令行中运行 curl http://127.0.0.1:8080/，这两种方式调试
GET http://127.0.0.1:8080/

### update_handler

PATCH http://127.0.0.1:8080/
Content-Type: application/json

{
  "age": 40,
}


PATCH http://localhost:8081/
Content-Type: application/json

{
  "skills": ["Rust"]
}
